language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t mattshine/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mattshine/docker-react npm run test