version: '3'
services:
    web:
        stdin_open: true # needed to keep the compose up
        build:
            context: . # current working directory
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app # maps this folder outside the container into the internal container folder
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]